plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - Ciclo de Estudos 🎯.md
  - Como aprender 📚.md
  - Study/How Computers Works/Computer Introduction 👾.md

remote_theme: pages-themes/minimal@v0.2.0
title: [Study Notes - Bernardo]
description: [My organization of my study notes]